### ISSUE TITLE
Feature of exclude public channels seems to be breaking even after implementing changes in compliance export in Mattermost.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-legal-hold#114]
@fmartingr While testing the master branch for this plugin, I found an issue regarding the changes in the PR #102 .
The functionality added of excluding public channels is not working and the user receives an error on disabling and saving it. Also, since there is an extra check to validate that the compliance export is enabled, even after enabling the same, the user receives the same error.
I am providing the screenshots for the same:-
![image](https://github.com/user-attachments/assets/370b505d-e89e-4c91-aac8-56fb9e2dbf24)

![image](https://github.com/user-attachments/assets/44acb8d3-7f59-415d-a748-e2ed954f8974)

Logs:-
{"timestamp":"2024-09-24 20:14:01.170 +05:30","level":"error","msg":"Compliance monitoring must be enabled on the Mattermost server in order to include public channels in a LegalHold","caller":"app/plugin_api.go:1007","plugin_id":"com.mattermost.plugin-legal-hold"}

This shows that the compliance export needs to be enabled, which already is, still user receives this error

**Comment by wiggin77** [comment]
@AayushChaudhary0001 @fmartingr reminder that we want Exclude Public Channels to be the default.

**Comment by fmartingr** [comment]
Hey @AayushChaudhary0001 you enabled Compilance Exports, not Compilance Monitoring. Please check it out with the other compilance feature while I make a PR to make error message more useful in this case.

**Comment by AayushChaudhary0001** [comment]
@fmartingr Yes it works well after enabling compilance monitoring. I think we should add this somewhere in documentation as well(since this does not have any slash command). And you can proceed for making an error message more descriptive in such a case.

**Comment by fmartingr** [comment]
> And you can proceed for making an error message more descriptive in such a case.

Just made #115
