### ISSUE TITLE
Get CI passing

### ISSUE THREAD

**Issue by grundleborg** [mattermost/mattermost-plugin-legal-hold#16]

**Comment by fmartingr** [comment]
CI is passing now, do we need to upload this plugin to AWS S3 for distribution? If not we could leverage the community-plugin-cd which only creates a github release.

cc: @wiggin77

**Comment by wiggin77** [comment]
> CI is passing now, do we need to upload this plugin to AWS S3 for distribution? If not we could leverage the [community-plugin-cd](https://github.com/mattermost/actions-workflows/blob/main/.github/workflows/community-plugin-cd.yml) which only creates a github release.
> 
> cc: @wiggin77 

We don't need the AWS upload.  Even the github release seems unnecessary on every pr.

**Comment by fmartingr** [comment]
> > CI is passing now, do we need to upload this plugin to AWS S3 for distribution? If not we could leverage the [community-plugin-cd](https://github.com/mattermost/actions-workflows/blob/main/.github/workflows/community-plugin-cd.yml) which only creates a github release.
> > cc: @wiggin77
> 
> We don't need the AWS upload. Even the github release seems unnecessary on every pr.

That would be for the CD on tagged releases. CI is already passing (except the delivery with requires AWS).

**Comment by fmartingr** [comment]
Correct configuration has been added, CI pipeline is now successful on master and CD pipeline should work as well.
