### ISSUE TITLE
What posts can a user have seen in a channel?

### ISSUE THREAD

**Issue by grundleborg** [mattermost/mattermost-plugin-legal-hold#27]
Currently when showing the posts a user will have seen in a channel, we include the period when the user was a member of the channel. However, a user can scroll up after joining a channel to see all posts before they joined back to the data retention window. So do we need to be cleverer here or is this an acceptable limitation?

**Comment by grundleborg** [comment]
We ought to review this sooner rather than later...

**Comment by wiggin77** [comment]
I have passed this question along to the customer for input.

**Comment by grundleborg** [comment]
Conclusion was: we are happy with how it is for now... Will reconsider if any subsequent customer feedback suggests we should.
