### ISSUE TITLE
Minor UX Improvements

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/mattermost-plugin-legal-hold#33]
1. When adding users to a legal hold, I don't think we should use the @ sign, just typing any user should do.
![image](https://github.com/mattermost/mattermost-plugin-legal-hold/assets/11034289/09d3352c-40cf-4959-8aa2-a3685fab1107)

2. For the edit, download, release buttons, we should use the icons and make the release button red. Or if that's too much work for now, atleast adding an 8px spacing between them and making the link color for release red should do.
![image](https://github.com/mattermost/mattermost-plugin-legal-hold/assets/11034289/01da0b7a-abb6-4adb-af80-78597b774f55)

3. The starting and ending inputs have different widths on the edit (where they should be the same).
![image](https://github.com/mattermost/mattermost-plugin-legal-hold/assets/11034289/d52e7ff1-4fb9-4afb-a636-d1f4970d8aa5)

4. Should add a border-radius 50px to the chip for the user chip in the users chip.

5. For the release legal hold, we should show the name of the legal hold you're releasing, otherwise if a user misclicks, he may end up deleting the incorrect legal hold (which may be a big issue.
![image](https://github.com/mattermost/mattermost-plugin-legal-hold/assets/11034289/fc4c7730-1694-4864-b812-57934bcd7853)

Designs here for reference:
https://www.figma.com/file/KRW3cvrmrGPfD96Ya2sBVi/Legal-Hold-Plugin?type=design&node-id=1-7&mode=design&t=Cx390rrufTJzNN1I-11

**Comment by grundleborg** [comment]
@asaadmahmood @jasonblais for point (1), adding users to the list, how do you want it to work? At the moment, it allows searching by any of the usual fields (no need to type `@`) and then displays them as `@username`. There are various options (nickname, first+last name, username). What would you like me to use?

**Comment by grundleborg** [comment]
I've done 3, 4 & 5. @asaadmahmood please could you share SVGs for the icons in (2) and the I can do that one too.

**Comment by asaadmahmood** [comment]
@grundleborg Do we have access to the compass design icons?
If so, the icon is:
`icon-download-outline` and `icon-pencil-outline`.
https://mattermost.github.io/compass-icons/

**Comment by grundleborg** [comment]
> @asaadmahmood @jasonblais for point (1), adding users to the list, how do you want it to work? At the moment, it allows searching by any of the usual fields (no need to type `@`) and then displays them as `@username`. There are various options (nickname, first+last name, username). What would you like me to use?

DIscussed with @wiggin77 , proposal is display like this `@username (FirstName LastName)`

**Comment by asaadmahmood** [comment]
@grundleborg That's fine, but an @ shouldn't be needed to show the autocomplete.
