### ISSUE TITLE
Require session when accessing Rest APIs

### ISSUE THREAD

**Issue by wiggin77** [mattermost/mattermost-plugin-legal-hold#51]
Currently the code[ checks for a HTTP header](https://github.com/mattermost/mattermost-plugin-legal-hold/blob/7f7b058e2f9991e34e85054437f55edf010c6ab5/server/api.go#L24) `Mattermost-User-ID`.  The permissions for that userID are checked to ensure they are an admin.  However, anyone can create a request with the userID of an admin and use the APIs.

The requester should be logged in and the permissions should be checked against the userID from the session.

**Comment by grundleborg** [comment]
@wiggin77 I think you might need to update the docs here https://developers.mattermost.com/integrate/plugins/components/server/best-practices/ as that seems to recommend this as the way of checking who the requesting user is.

**Comment by wiggin77** [comment]
Sorry @grundleborg, my mistake.  I didn't know about the magic done in mmserver to set that header for the incoming request.
