### ISSUE TITLE
Legal hold download button not working

### ISSUE THREAD

**Issue by wiggin77** [mattermost/mattermost-plugin-legal-hold#57]
Customer report:

> When I click the Download button next to an existing hold.. nothing happens. Should this cause a pop-up to appear and ask me where to save? Does it automatically save to my download location? I looked but did not find anything.

Will collect info re desktop versus browser, version, OS.

Server does not have attachments enabled.

**Comment by sadohert** [comment]
I setup a reproduction for this.

Mattermost `v7.8` release branch.
MYSQL DB
Small amount of test data.

Testing in a browser tab.

To get the legal hold job to run, I set the job time to a few minutes in the future.  Noticed this log entry when i "Saved":

```
{"timestamp":"2024-06-03 19:09:59.630 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:426","tag_value":"sysconsole_write_*_read"}
```


I watched the Mattermost logs as the time I set came and went, and didn't see any log entries informing me the job was running.  Maybe expected?

I saw that I could still click the download button so I clicked it, and Chrome gave me the attached warning:

<img width="1368" alt="image" src="https://github.com/mattermost/mattermost-plugin-legal-hold/assets/260544/e1bf3882-e2ab-4c03-8eb8-b877829cefef">

I wonder if BofA is running into the same.

**Comment by fmartingr** [comment]
I have downloaded countless holds during testing without issues, since it's a streaming response it should start right away. Maybe is a restriction on their systems?

**Comment by wiggin77** [comment]
> I have downloaded countless holds during testing without issues, since it's a streaming response it should start right away. Maybe is a restriction on their systems?

Possibly. First we need to try against desktop, and different browsers on multiple OS's.

**Comment by sadohert** [comment]
I see this error in the customer logs:

```
{"timestamp":"2024-06-03 19:32:42.898 Z","level":"error","msg":"invalid key/value pair","caller":"app/plugin_api.go:976","plugin_id":"com.mattermost.plugin-legal-hold","arg":"Error 1305 (42000): FUNCTION mattermost.split_part does not exist\nunable to get channel metadata\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/store/sqlstore.SQLStore.GetChannelMetadataForIDs\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/store/sqlstore/legal_hold.go:207\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold.(*Execution).UpdateIndexes\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold/legal_hold.go:265\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold.(*Execution).Execute\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold/legal_hold.go:68\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/jobs.(*LegalHoldJob).run\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/jobs/legal_hold_job.go:202\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*Job).run.func1\n\tgithub.com/mattermost/mattermost-plugin-api@v0.1.4/cluster/job.go:206\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*Job).run\n\tgithub.com/mattermost/mattermost-plugin-api@v0.1.4/cluster/job.go:216\nruntime.goexit\n\truntime/asm_amd64.s:1650"}
```

Could there be bad data from a prior version of the plugin?  I'm not sure they deleted  prior plugin version completely before installing the new version... could the KV format have changed?

**Comment by sadohert** [comment]
Full support packet is here:

https://drive.google.com/file/d/1XoOoIs70FgYmb072VysNLmTl9iRK4oVk/view?usp=sharing

**Comment by wiggin77** [comment]
> I see this error in the customer logs:
> 
> ```
> {"timestamp":"2024-06-03 19:32:42.898 Z","level":"error","msg":"invalid key/value pair","caller":"app/plugin_api.go:976","plugin_id":"com.mattermost.plugin-legal-hold","arg":"Error 1305 (42000): FUNCTION mattermost.split_part does not exist\nunable to get channel metadata\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/store/sqlstore.SQLStore.GetChannelMetadataForIDs\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/store/sqlstore/legal_hold.go:207\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold.(*Execution).UpdateIndexes\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold/legal_hold.go:265\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold.(*Execution).Execute\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/legalhold/legal_hold.go:68\ngithub.com/mattermost/mattermost-plugin-legal-hold/server/jobs.(*LegalHoldJob).run\n\tgithub.com/mattermost/mattermost-plugin-legal-hold/server/jobs/legal_hold_job.go:202\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*Job).run.func1\n\tgithub.com/mattermost/mattermost-plugin-api@v0.1.4/cluster/job.go:206\ngithub.com/mattermost/mattermost-plugin-api/cluster.(*Job).run\n\tgithub.com/mattermost/mattermost-plugin-api@v0.1.4/cluster/job.go:216\nruntime.goexit\n\truntime/asm_amd64.s:1650"}
> ```
> 
> Could there be bad data from a prior version of the plugin? I'm not sure they deleted prior plugin version completely before installing the new version... could the KV format have changed?

Yes, that is likely the issue.  There was a warning included with the 0.3.0 release notes:  https://github.com/mattermost/mattermost-plugin-legal-hold/releases/tag/v0.3.0

**Comment by wiggin77** [comment]
@sadohert actually, looking at the error log, it appears to be the same error as before the MySQL fix.  Are we sure they deployed the fixed version?

**Comment by wiggin77** [comment]
I believe this is the issue where no data gets collected until the job runs the next day.  The issue is documented in release notes and we will add a on demand button to run the job.
