### ISSUE TITLE
Legal hold plugin's functionality not working on cloud servers of MM

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-legal-hold#69]
While testing the master branch I got to know that the plugin's functionality is not working well on cloud servers. The ZIP file downloaded through the system console does not contains the data the user demands for. I am attaching a supporting video which explains complete scenario.

https://github.com/mattermost/mattermost-plugin-legal-hold/assets/116162036/63916e64-3d42-4cff-ba38-41115f47e274

**Comment by wiggin77** [comment]
@AayushChaudhary0001 are you using the API to trigger the job to run manually for your test as per this PR?  https://github.com/mattermost/mattermost-plugin-legal-hold/pull/43

Otherwise, when you set the time of day in the Hold, it will not run the job until that time the next day.

**Comment by mickmister** [comment]
@wiggin77 I'm thinking the same here. It seems the job just has not run yet in the case of the gif above. I've creates a PR to help surface the feature of running the job on demand https://github.com/mattermost/mattermost-plugin-legal-hold/pull/71

@AayushChaudhary0001 Can you please try this out and see if you experience the same issue?

**Comment by wiggin77** [comment]
@mickmister  We may need a button to trigger the job manually.  The API accessed via curl is too hard to discover.

**Comment by AayushChaudhary0001** [comment]
@mickmister I tried this way of running the job, and I was able to run it as many times as I wanted. But still I am facing the same issue, the file downloaded does not contain the data I am trying to fetch from the created legal hold configurations.

**Comment by wiggin77** [comment]
@mickmister does this fix https://github.com/mattermost/mattermost-plugin-legal-hold/issues/68 as well?

**Comment by mickmister** [comment]
@wiggin77 No this issue is essentially "the zip file is blank because the enumeration of files doesn't work". So _all_ files are missing from the zip file in this case, whereas there are "broken links" to files in the linked issue
